import "./globals.css";
import Header from "../component/Header/Header";
import RootStyleRegistry from "./RootStyleRegistry";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Rahma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <RootStyleRegistry>
          <div>
            <Header />
            <main>{children}</main>
          </div>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
